on:
  pull_request:
    types: [opened]

jobs:
  create-unit-test:
    runs-on: ubuntu-latest
    name: Create unit test
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35  
        with:
          separator: ','

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - uses: actions/checkout@v3
        
      - name: Generate unit test 
        uses: ./action.yaml
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }} # Get the Github Token from repository secrets
          rapidapi_key: ${{ secrets.RAPIDAPI_KEY}}
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

