on:
  pull_request:
    types: [opened]

jobs:
  acquire-necessary-info:
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      final_diff: ${{ steps.get-final-diff.outputs.final_diff }}
    name: Acquire necessary info
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35  
        with:
          separator: ','

      - name: Get final diff
        id: get-final-diff
        run: echo "::set-output name=final_diff:: |
        git diff ${{ github.event.pull_request.head.sha }}..${{ github.event.pull_request.base.sha }}"

  create-unit-test:
    runs-on: ubuntu-latest
    needs: acquire-necessary-info
    name: Create unit test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Generate unit test 
        uses: ./
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }} # Get the Github Token from repository secrets
          rapidapi_key: ${{ secrets.RAPIDAPI_KEY}} # Your RapidAPI Key from https://rapidapi.com/ldsds94/api/gptest1/pricing
          changed_files: ${{ needs.acquire-necessary-info.outputs.all_changed_files }}
          final_diff: ${{ needs.acquire-necessary-info.outputs.final_diff }}

