on:
  pull_request:
    types: [opened]

jobs:
  create-unit-test:
    name: Create unit test
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35  
        with:
          separator: ','

      - name: Get final diff
        id: get-final-diff
        run: |
          finalDiff=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }}) 
          finalDiff="${finalDiff//'%'/'%25'}"
          finalDiff="${finalDiff//$'\n'/'%0A'}"
          finalDiff="${finalDiff//$'\r'/'%0D'}"
          echo "final_diff=$finalDiff" >> $GITHUB_OUTPUT 
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        
      - name: Generate unit test 
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.repository }}
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
          final_diff: ${{ steps.get-final-diff.outputs.final_diff }}
